### PR TITLE
Character model

### PR DESCRIPTION
**Pull request by Erikad94**
#9 avec junit

### CODE REVIEW

**Comment by DrPandemic** [comment]
:+1:

**Comment by JesseEmond** [comment]
LGTM :+1:

**Comment by pellerinse2302** [comment]
MicLamb : please change the attribute order to match the backend pattern.

    name: {type: String, unique: true},
    nationality: String,
    race: {type: String, enum: ['humain', 'elf', 'dwarf']},
    profession: {type: String, enum: ['botanist', 'miner', 'forgeron', 'scribe', 'trader']},
    class: {type: String, enum: ['warrior', 'wizard', 'bard', 'priest', 'thief']},
    belief: String,
    max_hp: Number,
    skills: {type: [String], validate: validatorSkills},
    xp: Number

**Comment by bluespart** [comment]
We should probably get the character Id in the character sheet if we want to update the character server side.

**Comment by Baltazar510** [comment]
:+1:

**Comment by Erikad94** [comment]
:+1:

**Comment by JesseEmond** [comment]
@bluespart @MicLamb changes added. Please review when you have the time!

**Comment by DrPandemic** [comment]
Ton vote compte pas @Erikad94

**Comment by bluespart** [comment]
Changes look ok

**Comment by pellerinse2302** [comment]
Thanks for the change and sorry for my contemptuous attitude.

**Pull request merged**
