### PR TITLE
Auto Seed of the Database ;)

### PR DESCRIPTION
**Pull request by MicLamb**
You can now use the command "npm run seed" to feed your database with two users and 5 characters.

Email : MrGN@GN.com 
Password : password

Email : MrsGN@GN.com 
Password : password

Also edited the character tests to change "humain" to "human".

#42

### CODE REVIEW

**Comment by DrPandemic** [comment]
Thx, I don't know how to english! :+1:

**Comment by bluespart** [comment]
Looks good to me.

**Comment by Baltazar510** [comment]
Not much to add.

Ok pour jue

**Comment by pellerinse2302** [comment]
:+1:

**Pull request merged**
